sonar.projectKey=jnj-online
sonar.projectName=JnJ Online
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=src,firebase/test
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,firebase/test/**

sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,design/**,.github/**,.scannerwork/**,**/*.json,**/*.md,**/*.log
