import { Routes, Route, Navigate, HashRouter } from 'react-router-dom';
import { useEffect, useState } from 'react';
import '../styles/App.scss';
import { Homepage } from './Homepage';
import { Blog } from './Blog';
import { Navigation } from './Navigation';
import BlogPages from './BlogPages';
import { InvalidPage } from './InvalidPage';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

function googleSheetsLogic() {
  // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });
}


function App() {
  const [markdowns, setMarkdowns] = useState([]);
  const [spreadsheetData, setSpreadsheetData] = useState([]);

  useEffect(() => {
    fetch('/allFileNames.txt')
      .then((r) => r.text())
      .then(text  => {
        var array = text.split(/\r?\n/);
        array.pop();
        setMarkdowns(array)
      })
      .catch(err => console.log(err));
  },[]);

  (async function () {
    await someAsyncFunction();
  })();


  
  
  const routeMarkdownFiles = markdowns.map((file, index) =>
    <Route key={index} path={"blog/" + file} element={ <BlogPages post={file} /> } />
  );

  return (
    <HashRouter basename='/'>
      <div className="App">
        <div className='App-header'>
          <Navigation/>
        </div>
        <div className="App-body">
          <Routes>
            <Route path="*" element={ <InvalidPage/> } />
            <Route path="/" element={ <Navigate to="/home" /> } />
            <Route path="blog" element={ <Blog/> } />
            <Route path="/home" element={ <Homepage/> } />
            {routeMarkdownFiles}
          </Routes>
        </div>
      </div>
    </HashRouter>
    
  );
}

export default App;
